### ISSUE TITLE
Example using simple roscpp tutorial

### ISSUE THREAD

**Issue by marco-tranzatto** [larics/gdb_ros_publisher#1]
Hi @ojura , I saw your talk in roscon and I really appreciate your effort to share your knowledge about using rr with ROS!

I wanted to try it out with a simple [roscpp_tutorials](https://github.com/ros/ros_tutorials/tree/kinetic-devel/roscpp_tutorials), let's say the [listener node](https://github.com/ros/ros_tutorials/blob/kinetic-devel/roscpp_tutorials/listener/listener.cpp), but I'm definitely doing something wrong (see image below).  I managed to compile "gdb_ros_publisher_helper.so" and configure the required modules as stated [here](https://github.com/larics/gdb_ros_publisher#setting-up). I'm using Ubunut 16.04 with ROS Melodic.

Can you maybe provide some hints about how to run rr with this simple example?

Thanks,
Marco.

![screenshot_2018-10-29_18-09-03](https://user-images.githubusercontent.com/5328930/47667259-d5ed8500-dba5-11e8-94a2-50942da8b825.png)

**Comment by ojura** [comment]
Hi @marco-tranzatto, thank you for your interest!

`CPU 0x406e0 unknown` seems like it is an rr error described in this issue: https://github.com/mozilla/rr/issues/1921

It looks like you are using an older version of rr (probably the one from Ubuntu 16.04 repositories?) which does not support Intel Kaby Lake CPUs. I recommend installing the newest rr git master [from source](https://github.com/mozilla/rr/wiki/Building-And-Installing).

**Comment by marco-tranzatto** [comment]
Hi @ojura , thanks a lot for the suggestion! Before I installed rr via apt, but now after I installed it from source it works!

**Comment by ojura** [comment]
No problem! Feel free to leave more feedback if you encounter more issues or have an interesting use case.
